package com.myn.demo.springdemo.dao;

import com.myn.demo.springdemo.model.PtBenefitCoupon;

public interface PtBenefitCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_benefit_coupon
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_benefit_coupon
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    int insert(PtBenefitCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_benefit_coupon
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    int insertSelective(PtBenefitCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_benefit_coupon
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    PtBenefitCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_benefit_coupon
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    int updateByPrimaryKeySelective(PtBenefitCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_benefit_coupon
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    int updateByPrimaryKey(PtBenefitCoupon record);
}