server:
  port: 8087
  tomcat:
    max-connections: 500
  servlet:
    context-path: /service-myn
## 数据源：获取并管理数据库连接资源，池化数据源应配置连接池,此处不使用spring默认连接池Hikari，而是阿里Druid：使用三方starter 自己配置druid:包括数据源，事务管理器
spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://g1-off-ku-qa.dns.guazi.com:3324/20211208xinche_activity?autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: miaochenge
    password: cebce5b0
## 使用druid-starter，配置参数
    druid:
      test-on-borrow: true
  redis:
    client-type: jedis
    jedis:
      pool:
        enabled: true
        max-active: 8
        min-idle: 0
## 指定mapper.xml
mybatis:
  mapper-locations: classpath:mappers/*.xml

thread:
  pool:
    threadNamePrefix: test