package com.myn.demo.springdemo.model;

import java.math.BigDecimal;
import java.util.Date;

public class PtBenefitCoupon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.activity_id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.benefit_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer benefitType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.coupon_name
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private String couponName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.coupon_title
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private String couponTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.coupon_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private String couponType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.coupon_rule
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private String couponRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.coupon_status
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Boolean couponStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.receive_start_time
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Date receiveStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.receive_end_time
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Date receiveEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.effect_time_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private String effectTimeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.effect_start_time
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Date effectStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.effect_end_time
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Date effectEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.effect_days
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer effectDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.start_period
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer startPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.end_period
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer endPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.area_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer areaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.sms_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer smsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.identify
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer identify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.operator
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.creator
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.created_at
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.updated_at
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.benefit_package_id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer benefitPackageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.limit_count
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer limitCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.order_limit_content
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private String orderLimitContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.benefit_money
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Long benefitMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.is_deleted
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.goods_id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.goods_price
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.payment_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer paymentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.usage_scenario
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer usageScenario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.parent_id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_benefit_coupon.coupon_count
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    private Integer couponCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.id
     *
     * @return the value of pt_benefit_coupon.id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.id
     *
     * @param id the value for pt_benefit_coupon.id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.activity_id
     *
     * @return the value of pt_benefit_coupon.activity_id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.activity_id
     *
     * @param activityId the value for pt_benefit_coupon.activity_id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.benefit_type
     *
     * @return the value of pt_benefit_coupon.benefit_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getBenefitType() {
        return benefitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.benefit_type
     *
     * @param benefitType the value for pt_benefit_coupon.benefit_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setBenefitType(Integer benefitType) {
        this.benefitType = benefitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.coupon_name
     *
     * @return the value of pt_benefit_coupon.coupon_name
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.coupon_name
     *
     * @param couponName the value for pt_benefit_coupon.coupon_name
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName == null ? null : couponName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.coupon_title
     *
     * @return the value of pt_benefit_coupon.coupon_title
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public String getCouponTitle() {
        return couponTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.coupon_title
     *
     * @param couponTitle the value for pt_benefit_coupon.coupon_title
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setCouponTitle(String couponTitle) {
        this.couponTitle = couponTitle == null ? null : couponTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.coupon_type
     *
     * @return the value of pt_benefit_coupon.coupon_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public String getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.coupon_type
     *
     * @param couponType the value for pt_benefit_coupon.coupon_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setCouponType(String couponType) {
        this.couponType = couponType == null ? null : couponType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.coupon_rule
     *
     * @return the value of pt_benefit_coupon.coupon_rule
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public String getCouponRule() {
        return couponRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.coupon_rule
     *
     * @param couponRule the value for pt_benefit_coupon.coupon_rule
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setCouponRule(String couponRule) {
        this.couponRule = couponRule == null ? null : couponRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.coupon_status
     *
     * @return the value of pt_benefit_coupon.coupon_status
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Boolean getCouponStatus() {
        return couponStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.coupon_status
     *
     * @param couponStatus the value for pt_benefit_coupon.coupon_status
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setCouponStatus(Boolean couponStatus) {
        this.couponStatus = couponStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.receive_start_time
     *
     * @return the value of pt_benefit_coupon.receive_start_time
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Date getReceiveStartTime() {
        return receiveStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.receive_start_time
     *
     * @param receiveStartTime the value for pt_benefit_coupon.receive_start_time
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setReceiveStartTime(Date receiveStartTime) {
        this.receiveStartTime = receiveStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.receive_end_time
     *
     * @return the value of pt_benefit_coupon.receive_end_time
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Date getReceiveEndTime() {
        return receiveEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.receive_end_time
     *
     * @param receiveEndTime the value for pt_benefit_coupon.receive_end_time
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setReceiveEndTime(Date receiveEndTime) {
        this.receiveEndTime = receiveEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.effect_time_type
     *
     * @return the value of pt_benefit_coupon.effect_time_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public String getEffectTimeType() {
        return effectTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.effect_time_type
     *
     * @param effectTimeType the value for pt_benefit_coupon.effect_time_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setEffectTimeType(String effectTimeType) {
        this.effectTimeType = effectTimeType == null ? null : effectTimeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.effect_start_time
     *
     * @return the value of pt_benefit_coupon.effect_start_time
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Date getEffectStartTime() {
        return effectStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.effect_start_time
     *
     * @param effectStartTime the value for pt_benefit_coupon.effect_start_time
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setEffectStartTime(Date effectStartTime) {
        this.effectStartTime = effectStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.effect_end_time
     *
     * @return the value of pt_benefit_coupon.effect_end_time
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Date getEffectEndTime() {
        return effectEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.effect_end_time
     *
     * @param effectEndTime the value for pt_benefit_coupon.effect_end_time
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setEffectEndTime(Date effectEndTime) {
        this.effectEndTime = effectEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.effect_days
     *
     * @return the value of pt_benefit_coupon.effect_days
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getEffectDays() {
        return effectDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.effect_days
     *
     * @param effectDays the value for pt_benefit_coupon.effect_days
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setEffectDays(Integer effectDays) {
        this.effectDays = effectDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.start_period
     *
     * @return the value of pt_benefit_coupon.start_period
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getStartPeriod() {
        return startPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.start_period
     *
     * @param startPeriod the value for pt_benefit_coupon.start_period
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setStartPeriod(Integer startPeriod) {
        this.startPeriod = startPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.end_period
     *
     * @return the value of pt_benefit_coupon.end_period
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getEndPeriod() {
        return endPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.end_period
     *
     * @param endPeriod the value for pt_benefit_coupon.end_period
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setEndPeriod(Integer endPeriod) {
        this.endPeriod = endPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.area_type
     *
     * @return the value of pt_benefit_coupon.area_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.area_type
     *
     * @param areaType the value for pt_benefit_coupon.area_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setAreaType(Integer areaType) {
        this.areaType = areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.sms_type
     *
     * @return the value of pt_benefit_coupon.sms_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getSmsType() {
        return smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.sms_type
     *
     * @param smsType the value for pt_benefit_coupon.sms_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setSmsType(Integer smsType) {
        this.smsType = smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.identify
     *
     * @return the value of pt_benefit_coupon.identify
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getIdentify() {
        return identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.identify
     *
     * @param identify the value for pt_benefit_coupon.identify
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setIdentify(Integer identify) {
        this.identify = identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.operator
     *
     * @return the value of pt_benefit_coupon.operator
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.operator
     *
     * @param operator the value for pt_benefit_coupon.operator
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.creator
     *
     * @return the value of pt_benefit_coupon.creator
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.creator
     *
     * @param creator the value for pt_benefit_coupon.creator
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.created_at
     *
     * @return the value of pt_benefit_coupon.created_at
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.created_at
     *
     * @param createdAt the value for pt_benefit_coupon.created_at
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.updated_at
     *
     * @return the value of pt_benefit_coupon.updated_at
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.updated_at
     *
     * @param updatedAt the value for pt_benefit_coupon.updated_at
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.benefit_package_id
     *
     * @return the value of pt_benefit_coupon.benefit_package_id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getBenefitPackageId() {
        return benefitPackageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.benefit_package_id
     *
     * @param benefitPackageId the value for pt_benefit_coupon.benefit_package_id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setBenefitPackageId(Integer benefitPackageId) {
        this.benefitPackageId = benefitPackageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.limit_count
     *
     * @return the value of pt_benefit_coupon.limit_count
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getLimitCount() {
        return limitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.limit_count
     *
     * @param limitCount the value for pt_benefit_coupon.limit_count
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setLimitCount(Integer limitCount) {
        this.limitCount = limitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.order_limit_content
     *
     * @return the value of pt_benefit_coupon.order_limit_content
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public String getOrderLimitContent() {
        return orderLimitContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.order_limit_content
     *
     * @param orderLimitContent the value for pt_benefit_coupon.order_limit_content
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setOrderLimitContent(String orderLimitContent) {
        this.orderLimitContent = orderLimitContent == null ? null : orderLimitContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.benefit_money
     *
     * @return the value of pt_benefit_coupon.benefit_money
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Long getBenefitMoney() {
        return benefitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.benefit_money
     *
     * @param benefitMoney the value for pt_benefit_coupon.benefit_money
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setBenefitMoney(Long benefitMoney) {
        this.benefitMoney = benefitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.is_deleted
     *
     * @return the value of pt_benefit_coupon.is_deleted
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.is_deleted
     *
     * @param isDeleted the value for pt_benefit_coupon.is_deleted
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.goods_id
     *
     * @return the value of pt_benefit_coupon.goods_id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.goods_id
     *
     * @param goodsId the value for pt_benefit_coupon.goods_id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.goods_price
     *
     * @return the value of pt_benefit_coupon.goods_price
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.goods_price
     *
     * @param goodsPrice the value for pt_benefit_coupon.goods_price
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.payment_type
     *
     * @return the value of pt_benefit_coupon.payment_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.payment_type
     *
     * @param paymentType the value for pt_benefit_coupon.payment_type
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.usage_scenario
     *
     * @return the value of pt_benefit_coupon.usage_scenario
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getUsageScenario() {
        return usageScenario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.usage_scenario
     *
     * @param usageScenario the value for pt_benefit_coupon.usage_scenario
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setUsageScenario(Integer usageScenario) {
        this.usageScenario = usageScenario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.parent_id
     *
     * @return the value of pt_benefit_coupon.parent_id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.parent_id
     *
     * @param parentId the value for pt_benefit_coupon.parent_id
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_benefit_coupon.coupon_count
     *
     * @return the value of pt_benefit_coupon.coupon_count
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public Integer getCouponCount() {
        return couponCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_benefit_coupon.coupon_count
     *
     * @param couponCount the value for pt_benefit_coupon.coupon_count
     *
     * @mbg.generated Fri Mar 18 17:55:26 CST 2022
     */
    public void setCouponCount(Integer couponCount) {
        this.couponCount = couponCount;
    }
}